/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsMcqQuizRouteImport } from './routes/tools.mcq-quiz'
import { Route as ToolsFormulasRouteImport } from './routes/tools.formulas'
import { Route as ToolsDiagramsRouteImport } from './routes/tools.diagrams'
import { Route as ToolsConvertersRouteImport } from './routes/tools.converters'
import { Route as ToolsCalculatorsRouteImport } from './routes/tools.calculators'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ExamResultResultIdRouteImport } from './routes/exam-result.$resultId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ExamPaperIdIndexRouteImport } from './routes/exam.$paperId.index'
import { Route as SubjectsSlugShortNotesRouteImport } from './routes/subjects.$slug.short-notes'
import { Route as SubjectsSlugPastPapersRouteImport } from './routes/subjects.$slug.past-papers'
import { Route as SubjectsSlugModelPapersRouteImport } from './routes/subjects.$slug.model-papers'
import { Route as SubjectsSlugExamsRouteImport } from './routes/subjects.$slug.exams'
import { Route as ExamPaperIdStartRouteImport } from './routes/exam.$paperId.start'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMcqQuizRoute = ToolsMcqQuizRouteImport.update({
  id: '/tools/mcq-quiz',
  path: '/tools/mcq-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFormulasRoute = ToolsFormulasRouteImport.update({
  id: '/tools/formulas',
  path: '/tools/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiagramsRoute = ToolsDiagramsRouteImport.update({
  id: '/tools/diagrams',
  path: '/tools/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsConvertersRoute = ToolsConvertersRouteImport.update({
  id: '/tools/converters',
  path: '/tools/converters',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCalculatorsRoute = ToolsCalculatorsRouteImport.update({
  id: '/tools/calculators',
  path: '/tools/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/subjects/$slug',
  path: '/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResultResultIdRoute = ExamResultResultIdRouteImport.update({
  id: '/exam-result/$resultId',
  path: '/exam-result/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPaperIdIndexRoute = ExamPaperIdIndexRouteImport.update({
  id: '/exam/$paperId/',
  path: '/exam/$paperId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugShortNotesRoute = SubjectsSlugShortNotesRouteImport.update({
  id: '/short-notes',
  path: '/short-notes',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugPastPapersRoute = SubjectsSlugPastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugModelPapersRoute = SubjectsSlugModelPapersRouteImport.update({
  id: '/model-papers',
  path: '/model-papers',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugExamsRoute = SubjectsSlugExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const ExamPaperIdStartRoute = ExamPaperIdStartRouteImport.update({
  id: '/exam/$paperId/start',
  path: '/exam/$paperId/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam-result/$resultId': typeof ExamResultResultIdRoute
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/tools/calculators': typeof ToolsCalculatorsRoute
  '/tools/converters': typeof ToolsConvertersRoute
  '/tools/diagrams': typeof ToolsDiagramsRoute
  '/tools/formulas': typeof ToolsFormulasRoute
  '/tools/mcq-quiz': typeof ToolsMcqQuizRoute
  '/admin/': typeof AdminIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/exam/$paperId/start': typeof ExamPaperIdStartRoute
  '/subjects/$slug/exams': typeof SubjectsSlugExamsRoute
  '/subjects/$slug/model-papers': typeof SubjectsSlugModelPapersRoute
  '/subjects/$slug/past-papers': typeof SubjectsSlugPastPapersRoute
  '/subjects/$slug/short-notes': typeof SubjectsSlugShortNotesRoute
  '/exam/$paperId/': typeof ExamPaperIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam-result/$resultId': typeof ExamResultResultIdRoute
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/tools/calculators': typeof ToolsCalculatorsRoute
  '/tools/converters': typeof ToolsConvertersRoute
  '/tools/diagrams': typeof ToolsDiagramsRoute
  '/tools/formulas': typeof ToolsFormulasRoute
  '/tools/mcq-quiz': typeof ToolsMcqQuizRoute
  '/admin': typeof AdminIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/exam/$paperId/start': typeof ExamPaperIdStartRoute
  '/subjects/$slug/exams': typeof SubjectsSlugExamsRoute
  '/subjects/$slug/model-papers': typeof SubjectsSlugModelPapersRoute
  '/subjects/$slug/past-papers': typeof SubjectsSlugPastPapersRoute
  '/subjects/$slug/short-notes': typeof SubjectsSlugShortNotesRoute
  '/exam/$paperId': typeof ExamPaperIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam-result/$resultId': typeof ExamResultResultIdRoute
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/tools/calculators': typeof ToolsCalculatorsRoute
  '/tools/converters': typeof ToolsConvertersRoute
  '/tools/diagrams': typeof ToolsDiagramsRoute
  '/tools/formulas': typeof ToolsFormulasRoute
  '/tools/mcq-quiz': typeof ToolsMcqQuizRoute
  '/admin/': typeof AdminIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/exam/$paperId/start': typeof ExamPaperIdStartRoute
  '/subjects/$slug/exams': typeof SubjectsSlugExamsRoute
  '/subjects/$slug/model-papers': typeof SubjectsSlugModelPapersRoute
  '/subjects/$slug/past-papers': typeof SubjectsSlugPastPapersRoute
  '/subjects/$slug/short-notes': typeof SubjectsSlugShortNotesRoute
  '/exam/$paperId/': typeof ExamPaperIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/admin/login'
    | '/exam-result/$resultId'
    | '/subjects/$slug'
    | '/tools/calculators'
    | '/tools/converters'
    | '/tools/diagrams'
    | '/tools/formulas'
    | '/tools/mcq-quiz'
    | '/admin/'
    | '/subjects/'
    | '/tools/'
    | '/exam/$paperId/start'
    | '/subjects/$slug/exams'
    | '/subjects/$slug/model-papers'
    | '/subjects/$slug/past-papers'
    | '/subjects/$slug/short-notes'
    | '/exam/$paperId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/admin/login'
    | '/exam-result/$resultId'
    | '/subjects/$slug'
    | '/tools/calculators'
    | '/tools/converters'
    | '/tools/diagrams'
    | '/tools/formulas'
    | '/tools/mcq-quiz'
    | '/admin'
    | '/subjects'
    | '/tools'
    | '/exam/$paperId/start'
    | '/subjects/$slug/exams'
    | '/subjects/$slug/model-papers'
    | '/subjects/$slug/past-papers'
    | '/subjects/$slug/short-notes'
    | '/exam/$paperId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/admin/login'
    | '/exam-result/$resultId'
    | '/subjects/$slug'
    | '/tools/calculators'
    | '/tools/converters'
    | '/tools/diagrams'
    | '/tools/formulas'
    | '/tools/mcq-quiz'
    | '/admin/'
    | '/subjects/'
    | '/tools/'
    | '/exam/$paperId/start'
    | '/subjects/$slug/exams'
    | '/subjects/$slug/model-papers'
    | '/subjects/$slug/past-papers'
    | '/subjects/$slug/short-notes'
    | '/exam/$paperId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ExamResultResultIdRoute: typeof ExamResultResultIdRoute
  SubjectsSlugRoute: typeof SubjectsSlugRouteWithChildren
  ToolsCalculatorsRoute: typeof ToolsCalculatorsRoute
  ToolsConvertersRoute: typeof ToolsConvertersRoute
  ToolsDiagramsRoute: typeof ToolsDiagramsRoute
  ToolsFormulasRoute: typeof ToolsFormulasRoute
  ToolsMcqQuizRoute: typeof ToolsMcqQuizRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ExamPaperIdStartRoute: typeof ExamPaperIdStartRoute
  ExamPaperIdIndexRoute: typeof ExamPaperIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/mcq-quiz': {
      id: '/tools/mcq-quiz'
      path: '/tools/mcq-quiz'
      fullPath: '/tools/mcq-quiz'
      preLoaderRoute: typeof ToolsMcqQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/formulas': {
      id: '/tools/formulas'
      path: '/tools/formulas'
      fullPath: '/tools/formulas'
      preLoaderRoute: typeof ToolsFormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/diagrams': {
      id: '/tools/diagrams'
      path: '/tools/diagrams'
      fullPath: '/tools/diagrams'
      preLoaderRoute: typeof ToolsDiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/converters': {
      id: '/tools/converters'
      path: '/tools/converters'
      fullPath: '/tools/converters'
      preLoaderRoute: typeof ToolsConvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/calculators': {
      id: '/tools/calculators'
      path: '/tools/calculators'
      fullPath: '/tools/calculators'
      preLoaderRoute: typeof ToolsCalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/subjects/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-result/$resultId': {
      id: '/exam-result/$resultId'
      path: '/exam-result/$resultId'
      fullPath: '/exam-result/$resultId'
      preLoaderRoute: typeof ExamResultResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$paperId/': {
      id: '/exam/$paperId/'
      path: '/exam/$paperId'
      fullPath: '/exam/$paperId/'
      preLoaderRoute: typeof ExamPaperIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug/short-notes': {
      id: '/subjects/$slug/short-notes'
      path: '/short-notes'
      fullPath: '/subjects/$slug/short-notes'
      preLoaderRoute: typeof SubjectsSlugShortNotesRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/past-papers': {
      id: '/subjects/$slug/past-papers'
      path: '/past-papers'
      fullPath: '/subjects/$slug/past-papers'
      preLoaderRoute: typeof SubjectsSlugPastPapersRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/model-papers': {
      id: '/subjects/$slug/model-papers'
      path: '/model-papers'
      fullPath: '/subjects/$slug/model-papers'
      preLoaderRoute: typeof SubjectsSlugModelPapersRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/exams': {
      id: '/subjects/$slug/exams'
      path: '/exams'
      fullPath: '/subjects/$slug/exams'
      preLoaderRoute: typeof SubjectsSlugExamsRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/exam/$paperId/start': {
      id: '/exam/$paperId/start'
      path: '/exam/$paperId/start'
      fullPath: '/exam/$paperId/start'
      preLoaderRoute: typeof ExamPaperIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubjectsSlugRouteChildren {
  SubjectsSlugExamsRoute: typeof SubjectsSlugExamsRoute
  SubjectsSlugModelPapersRoute: typeof SubjectsSlugModelPapersRoute
  SubjectsSlugPastPapersRoute: typeof SubjectsSlugPastPapersRoute
  SubjectsSlugShortNotesRoute: typeof SubjectsSlugShortNotesRoute
}

const SubjectsSlugRouteChildren: SubjectsSlugRouteChildren = {
  SubjectsSlugExamsRoute: SubjectsSlugExamsRoute,
  SubjectsSlugModelPapersRoute: SubjectsSlugModelPapersRoute,
  SubjectsSlugPastPapersRoute: SubjectsSlugPastPapersRoute,
  SubjectsSlugShortNotesRoute: SubjectsSlugShortNotesRoute,
}

const SubjectsSlugRouteWithChildren = SubjectsSlugRoute._addFileChildren(
  SubjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ExamResultResultIdRoute: ExamResultResultIdRoute,
  SubjectsSlugRoute: SubjectsSlugRouteWithChildren,
  ToolsCalculatorsRoute: ToolsCalculatorsRoute,
  ToolsConvertersRoute: ToolsConvertersRoute,
  ToolsDiagramsRoute: ToolsDiagramsRoute,
  ToolsFormulasRoute: ToolsFormulasRoute,
  ToolsMcqQuizRoute: ToolsMcqQuizRoute,
  AdminIndexRoute: AdminIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ExamPaperIdStartRoute: ExamPaperIdStartRoute,
  ExamPaperIdIndexRoute: ExamPaperIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
